- name: Start container {{ pi_hole_container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ pi_hole_container_name }}"
    image: pihole/pihole:latest
    state: started
    restart: true
    restart_policy: always
    network_mode: host
    mounts:
      - source: "{{ pi_hole_container_name }}_dnsmasq"
        target: /etc/dnsmasq.d
        type: volume
      - source: "{{ pi_hole_container_name }}_pihole"
        target: /etc/pihole
        type: volume
    env:
      DNSMASQ_LISTENING: all
      TZ: "{{ pi_hole_time_zone }}"
      WEBPASSWORD: "{{ pi_hole_admin_web_password }}"
      WEB_PORT: "{{ pi_hole_web_port | string }}"
      PIHOLE_UID: "{{ pi_hole_uid | string }}"
      PIHOLE_GID: "{{ pi_hole_uid | string }}"
    capabilities:
      - NET_ADMIN

- name: Template custom.list for local DNS entries
  become: true
  ansible.builtin.template:
    src: custom.list.j2
    dest: /var/lib/docker/volumes/{{ pi_hole_container_name }}_pihole/_data/custom.list
    mode: '644'
    owner: pihole
    group: pihole