- name: Create pihole group
  become: true
  ansible.builtin.group:
    gid: "{{ pi_hole_gid }}"
    name: pihole
    state: present

- name: Create pihole user
  become: true
  ansible.builtin.user:
    uid: "{{ pi_hole_uid }}"
    name: pihole
    shell: /bin/bash
    group: pihole
    state: present
