- name: Start container {{ pi_hole_container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ pi_hole_container_name }}"
    image: pihole/pihole:latest
    state: started
    restart: true
    network_mode: host
    mounts:
      - source: "{{ pi_hole_container_name }}_dnsmasq"
        target: /etc/dnsmasq.d
        type: volume
      - source: "{{ pi_hole_container_name }}_pihole"
        target: /etc/pihole
        type: volume
    env:
      TZ: America/Edmonton
      WEBPASSWORD: "{{ pi_hole_admin_web_password }}"
      WEB_PORT: "{{ pi_hole_admin_web_port | string }}"
      DNSMASQ_LISTENING: all
      PIHOLE_UID: "{{ pi_hole_uid | string }}"
      PIHOLE_GID: "{{ pi_hole_gid | string }}"
    capabilities:
      - NET_ADMIN

- name: Template custom.list for local DNS entries
  become: true
  ansible.builtin.template:
    src: custom.list.j2
    dest: /var/lib/docker/volumes/{{ pi_hole_container_name }}_pihole/_data/custom.list
    mode: '644'
    owner: "{{ pi_hole_user }}"
    group: "{{ pi_hole_user }}"
