- name: Start container {{ container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: pihole/pihole:{{ version }}
    state: "{{ container_state }}"
    restart: "{{ container_restart }}"
    restart_policy: "{{ container_restart_policy }}"
    network_mode: bridge
    published_ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "{{ web_host_port }}:80"
    mounts:
      - source: "{{ container_name }}_dnsmasq"
        target: /etc/dnsmasq.d
        type: volume
      - source: "{{ container_name }}_pihole"
        target: /etc/pihole
        type: volume
    env: "{{ container_env }}"
    capabilities:
      - NET_ADMIN

- name: Template custom.list for local DNS entries
  become: true
  ansible.builtin.template:
    src: custom.list.j2
    dest: /var/lib/docker/volumes/{{ container_name }}_pihole/_data/custom.list
    mode: '644'
    owner: pihole
    group: pihole
  notify: Restart container
