- name: Set the container environment
  set_fact:
    container_env:
      DNSMASQ_LISTENING: all
      TZ: "{{ time_zone }}"
      WEBPASSWORD: "{{ admin_password }}"
      WEB_PORT: "{{ web_host_port | string }}"
      PIHOLE_UID: "{{ uid | string }}"
      PIHOLE_GID: "{{ uid | string }}"
      FTLCONF_LOCAL_IPV4: "{{ ansible_default_ipv4.address }}"

- name: Start container {{ container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: pihole/pihole:{{ version }}
    state: "{{ container_state }}"
    restart: "{{ container_restart }}"
    restart_policy: "{{ container_restart_policy }}"
    network_mode: host
    mounts:
      - source: "{{ container_name }}_dnsmasq"
        target: /etc/dnsmasq.d
        type: volume
      - source: "{{ container_name }}_pihole"
        target: /etc/pihole
        type: volume
    env: "{{ container_env }}"
    capabilities:
      - NET_ADMIN

