- name: Create minecraft group
  become: true
  ansible.builtin.group:
    gid: "{{ mc_gid }}"
    name: minecraft
    state: present

- name: Create minecraft user
  become: true
  ansible.builtin.user:
    uid: "{{ mc_uid }}"
    name: minecraft
    shell: /bin/bash
    group: minecraft
    state: present
