- name: Start container {{ mc_container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ mc_container_name }}"
    image: itzg/minecraft-server:latest
    state: started
    restart: true
    network_mode: bridge
    restart_policy: always
    tty: true
    interactive: true
    ports:
      - '{{ mc_port }}:25565'
    mounts:
      - source: "{{ mc_container_name }}_data"
        target: /data
        type: volume
    env:
      EULA: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      MEMORY: "{{ mc_jvm_memory_gb | string }}G"
      UID: "{{ mc_uid | string }}"
      GID: "{{ mc_uid | string }}"
      SEED: "{{ mc_seed | string }}"
      DIFFICULTY: "{{ mc_difficulty }}"
      OPS: "{{ mc_ops | join(',') }}"
      OVERRIDE_OPS: "TRUE"
      ICON: "{{ mc_icon_url | default(omit, true) }}"
      OVERRIDE_ICON: "TRUE"
