- name: Create minecraft group
  become: true
  ansible.builtin.group:
    gid: "{{ minecraft_server_container_gid }}"
    name: minecraft
    state: present

- name: Create minecraft user
  become: true
  ansible.builtin.user:
    uid: "{{ minecraft_server_container_uid }}"
    name: minecraft
    shell: /bin/bash
    group: minecraft
    state: present

- name: Set the container environment
  set_fact:
    container_env:
      EULA: "TRUE"
      ALLOW_FLIGHT: "TRUE"
      MEMORY: "{{ minecraft_server_memory_gb | string }}G"
      UID: "{{ minecraft_server_container_uid | string }}"
      GID: "{{ minecraft_server_container_gid | string }}"
      SEED: "{{ minecraft_server_seed | string }}"
      DIFFICULTY: "{{ minecraft_server_difficulty }}"
      OPS: "{{ minecraft_server_ops | join(',') }}"
      OVERRIDE_OPS: "TRUE"
      ICON: "{{ minecraft_server_icon_url }}"
      OVERRIDE_ICON: "TRUE"

- name: Create container {{ minecraft_server_container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ minecraft_server_container_name }}"
    image: itzg/minecraft-server:latest
    state: "{{ container_state }}"
    restart: "{{ container_restart }}"
    network_mode: bridge
    restart_policy: "{{ minecraft_server_container_restart_policy }}"
    tty: true
    interactive: true
    ports:
      - '{{ minecraft_server_host_port }}:25565'
    mounts:
      - source: "{{ minecraft_server_container_name }}"
        target: /data
        type: volume
    env: "{{ container_env }}"