- name: Template /etc/systemd/resolved.conf
  become: true
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    mode: '644'
    owner: root
    group: root
  notify: Restart systemd-resolved

- name: Copy /etc/ssh/sshd_config.d
  become: true
  ansible.builtin.copy:
    src: sshd_config.d
    dest: /etc/ssh
    directory_mode: '755'
    mode: '600'
    owner: root
    group: root
  notify:  Restart sshd

- name: Flush handlers
  meta: flush_handlers

- name: Install mount utils
  become: true
  apt:
    name: 
      - nfs-common
      - cifs-utils
    update_cache: true

- name: Ensure CIFS mount targets exists
  become: true
  file:
    path: "{{ item.target }}"
    owner: root
    group: root
    mode: "750"
    recurse: true
    state: directory
  with_items: "{{ cifs_mounts }}"

- name: Mount CIFS shares
  become: true
  ansible.posix.mount:
    src: "{{ item.source }}"
    path: "{{ item.target }}"
    opts: "username={{ cifs_username }},password={{ cifs_password }},{{ item.permissions }},file_mode={{ item.file_mode }},dir_mode={{ item.file_mode }},vers=3"
    fstype: cifs
    state: mounted
  with_items: "{{ cifs_mounts }}"