- name: Create heimdall group
  become: true
  ansible.builtin.group:
    name: heimdall
    state: present

- name: Create heimdall user
  become: true
  ansible.builtin.user:
    name: heimdall
    shell: /bin/bash
    group: heimdall
    state: present

- name: Get user details
  ansible.builtin.getent:
    database: passwd
    key: heimdall

- name: Get group details
  getent:
    database: group
    key: heimdall

- name: Set user and group id
  set_fact:
    container_uid: "{{ ansible_facts.getent_passwd.heimdall.1 }}"
    container_gid: "{{ ansible_facts.getent_group.heimdall.1 }}"

- name: Set the container environment
  set_fact:
    container_env:
      PUID: "{{ container_uid }}"
      PGID: "{{ container_gid }}"
      TZ: "{{ time_zone }}"

- name: Create container {{ heimdall_container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ heimdall_container_name }}"
    image: lscr.io/linuxserver/heimdall:{{ heimdall_container_version }}
    state: "{{ container_state }}"
    restart: "{{ container_restart }}"
    restart_policy: "{{ heimdall_container_restart_policy }}"
    network_mode: bridge
    published_ports: "{{ heimdall_container_ports }}"
    mounts:
      - source: "{{ heimdall_container_name }}_config"
        target: /config
        type: volume
    env: "{{ container_env }}"
