argument_specs:
  main:
    options:
      mc_container_name:
        type: str
        required: true
        description: The name for an existing or new Minecraft server container

      mc_uid:
        type: int
        required: true
        description: uid to set for the 'minecraft' user account, to run the server with

      mc_gid:
        type: int
        required: true
        description: gid to set for the 'minecraft' group, to run the server with

      mc_seed:
        type: int
        default: 1785852800490497919
        description: The seed to be used for world generation

      mc_jvm_memory_gb:
        type: int
        default: 2
        description: Gigabyte value to set for JVM Xms and Xmx on server start. Defaults to 2GB

      mc_ops:
        type: list
        elements: str
        default: []
        description: A list of usernames to be granted operator privileges on the server

      mc_difficulty:
        type: str
        default: normal
        description: The difficulty to set on the server. Defaults to normal

      mc_icon_url:
        type: str
        description: The URL for an icon to set for the server in the connections list
