- name: Restart systemd-resolved
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted

- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: ssh
    state: restarted