- name: Start container {{ portainer_container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ portainer_container_name }}"
    image: portainer/portainer-ce:latest
    state: started
    restart: true
    restart_policy: always
    network_mode: bridge
    ports:
      - "{{ portainer_agent_port }}:8000"
      - "{{ portainer_web_port }}:9443"
    mounts:
      - source: "{{ portainer_container_name }}_data"
        target: /data
        type: volume
      - source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        type: bind