- name: Start container {{ container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: portainer/portainer-ce:{{ version }}
    state: "{{ container_state }}"
    restart: "{{ container_restart }}"
    restart_policy: "{{ container_restart_policy }}"
    network_mode: bridge
    ports:
      - "{{ web_host_port }}:9443"
      - "{{ agent_host_port }}:8000"
    mounts:
      - source: "{{ container_name }}_data"
        target: /data
        type: volume
      - source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        type: bind
  register: portainer_container

- set_fact:
    portainer_api_base_url: https://{{ portainer_container.container.NetworkSettings.IPAddress }}:{{ web_host_port }}/api

- name: Initialize admin user password
  uri:
    url: "{{ portainer_api_base_url }}/users/admin/init"
    method: POST
    validate_certs: false
    body_format: json
    body: 
      Username: "{{ admin_user }}"
      Password: "{{ admin_password }}"
    status_code: 
      - 200
      - 409

- name: Generate authentication token
  uri:
    url: "{{ portainer_api_base_url }}/auth"
    method: POST
    validate_certs: false
    return_content: true
    body_format: json
    body: 
      Username: "{{ admin_user }}"
      Password: "{{ admin_password }}"
  register: auth_token
