- name: Create container {{ npm_container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ npm_container_name }}"
    image: jc21/nginx-proxy-manager:{{ npm_container_version }}
    state: "{{ container_state }}"
    restart: "{{ container_restart }}"
    restart_policy: "{{ npm_container_restart_policy }}"
    network_mode: bridge
    ports:
      - "{{ npm_web_port }}:81"
      - 80:80
      - 443:443
    mounts:
      - source: "{{ npm_container_name }}_data"
        target: /data
        type: volume
      - source: "{{ npm_container_name }}_letsencrypt"
        target: /etc/letsencrypt
        type: volume
