# - name: Start nginx-proxy-manager container
#   become: true
#   community.docker.docker_container:
#     name: nginx-proxy-manager
#     image: jc21/nginx-proxy-manager:latest
#     state: started
#     restart: true
#     ports:
#       - 80:80
#       - 81:81
#       - 443:443
#     mounts:
#       - source: /var/tmp
#         target: /var/tmp

#       - "{{ docker_user_home_dir | regex_replace('/+$', '') }}/data:/data"
#       - "{{ docker_user_home_dir | regex_replace('/+$', '') }}/letsencrypt:/etc/letsencrypt"
