- name: Start container {{ npm_container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ npm_container_name }}"
    image: jc21/nginx-proxy-manager:latest
    state: started
    restart: true
    network_mode: bridge
    ports:
      - 80:80
      - 81:81
      - 443:443
    mounts:
      - source: "{{ npm_container_name }}_data"
        target: /data
        type: volume
      - source: "{{ npm_container_name }}_letsencrypt"
        target: /etc/letsencrypt
        type: volume
