- name: Start container {{ container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: jc21/nginx-proxy-manager:latest
    state: started
    restart: true
    ports:
      - 80:80
      - 81:81
      - 443:443
    mounts:
      - target: /data
        type: volume
      - target: /etc/letsencrypt
        type: volume
