- name: Template /etc/systemd/resolved.conf
  become: true
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    mode: '644'
    owner: root
    group: root

- name: Ensure the systemd-resolved service is restarted and enabled
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
    enabled: true

- name: Template /etc/systemd/network/00-static.network
  become: true
  ansible.builtin.template:
    src: 00-static.network.j2
    dest: /etc/systemd/network/00-static.network
    mode: '644'
    owner: root
    group: root

- name: Ensure the systemd-networkd service is restarted and enabled
  become: true
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted
    enabled: true
