- name: Ensure the systemd-resolved service is started and enabled
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    state: started
    enabled: true

- name: Template /etc/systemd/resolved.conf
  become: true
  ansible.builtin.template:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf
    mode: '644'
    owner: root
    group: root
  notify: Ensure the systemd-resolved service is restarted
