- name: Template /etc/systemd/resolved.conf
  become: true
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    mode: '644'
    owner: root
    group: root
  notify: Ensure the systemd-resolved service is restarted
