- name: Ensure the /usr/lib/systemd/system/docker.service.d drop-in directory exists
  become: true
  file:
    path: /usr/lib/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Template the /usr/lib/systemd/system/docker.service.d/docker.conf override file
  become: true
  template:
    src: docker.conf.j2
    dest: /usr/lib/systemd/system/docker.service.d/docker.conf
    owner: root
    group: root
    mode: '755'
  notify: Ensure the docker service is reloaded
