pi_hole_web_host_port: 80
pi_hole_container_restart_policy: always
pi_hole_container_version: latest
time_zone: America/Edmonton
pi_hole_local_dns_records: []
container_restart: false
container_state: started