- name: Set the container environment
  set_fact:
    container_env:
      PASSWORD: "{{ flame_password }}"

- name: Create container {{ flame_container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ flame_container_name }}"
    image: pawelmalak/flame:{{ flame_container_version }}
    state: "{{ container_state }}"
    restart: "{{ container_restart }}"
    restart_policy: "{{ flame_container_restart_policy }}"
    network_mode: bridge
    published_ports: "{{ flame_container_ports }}"
    mounts:
      - source: "{{ flame_container_name }}_data"
        target: /app/data
        type: volume
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
    env: "{{ container_env }}"