- name: Create plex group
  become: true
  ansible.builtin.group:
    gid: "{{ plex_container_gid }}"
    name: plex
    state: present

- name: Create plex user
  become: true
  ansible.builtin.user:
    uid: "{{ plex_container_uid }}"
    name: plex
    shell: /bin/bash
    group: plex
    state: present

- name: Set the container environment
  set_fact:
    container_env:
      PUID: "{{ plex_container_uid }}"
      PGID: "{{ plex_container_gid }}"
      VERSION: docker
      PLEX_CLAIM: "{{ plex_claim_token }}"
      TZ: "{{ time_zone }}"

- name: Create container {{ plex_container_name }}
  become: true
  community.docker.docker_container:
    name: "{{ plex_container_name }}"
    image: lscr.io/linuxserver/plex:{{ plex_container_version }}
    state: "{{ container_state }}"
    restart: "{{ container_restart }}"
    restart_policy: "{{ plex_container_restart_policy }}"
    network_mode: bridge
    published_ports:
      - "{{ plex_web_host_port }}:32400"
      - "1900:1900/udp"
      - "5353:5353/udp"
      - "8324:8324"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469"
    mounts: "{{ plex_container_mounts }}"